### PR TITLE
Support of  new spring-data-commons API (v2) (breaks downward compability)

### PR DESCRIPTION
**Pull request by mueller-jens**

### CODE REVIEW

**Comment by rwitzel** [comment]
Hi, Jens! Thank you for your contribution!

Do you mind to update the version in pom.xml and build.gradle to 1.0.0-SNAPSHOT? The library upgrade is an API change apparently.

**Comment by mueller-jens** [comment]
Yes i will do so this evening

**Comment by mueller-jens** [comment]
Hi Rodrigo, i have done the changes.

**Comment by mueller-jens** [comment]
Hi Rodrigo, one build faild, because of the new API uses Optionals, so it is not compileable with java7

**Comment by rwitzel** [comment]
@mueller-jens Hi Jens, thank you for the upgrade to Java8. Sorry for the delay. Could you

- [x] remove oraclejdk7 from travis.yml (so that the build is successful), and
- [x] update the section Prerequisites  in the README.md (Java 8 now)? 

Then the PR is ready for the merge.

**Comment by mueller-jens** [comment]
@rwitzel Hi I have changed to openjdk8 because oraclejdk8 is not longer supported. First try was to move to java 9 or higer but it doesn't work with gradle, so I have also raised the gradle version. hopefully it is ok for you

**Comment by rwitzel** [comment]
Thank you, Jens! Highly appreciated!

**Pull request merged**
